services:
  swoole-php:
    build:
      context: .
      dockerfile: ./docker/images/php/Dockerfile
    ports:
      - 8101:8101
    volumes:
      - ./app/php/:/app
  php-cli:
    build:
      context: .
      dockerfile: ./docker/images/php-cli/Dockerfile
    ports:
      - 8104:8101
    volumes:
      - ./app/php-cli/:/app
  go-app:
    build:
      context: .
      dockerfile: ./docker/images/golang/Dockerfile
    ports:
      - 8102:8101
    volumes:
      - ./app/golang/:/app
  dotnet-app:
    build:
      context: .
      dockerfile: ./docker/images/dotnet/Dockerfile
    ports:
      - "8103:8101"
    volumes:
      - ./app/dotnet/:/app